if(sessionStorage.getItem("btc_logged_in")!=="1")location.href="login.html";
const $=id=>document.getElementById(id),API="https://api.binance.com";let interval="1m",chart,series,ws;
function theme(){const light=document.body.classList.contains("light");chart&&chart.applyOptions({layout:{background:{color:light?"#fff":"#101621"},textColor:light?"#687385":"#8b97aa"},grid:{vertLines:{color:light?"#eee":"#18202d"},horzLines:{color:light?"#eee":"#18202d"}}})}
function init(){const light=localStorage.getItem("theme")==="light";document.body.classList.toggle("light",light);chart=LightweightCharts.createChart($("chart"),{layout:{background:{color:light?"#fff":"#101621"},textColor:light?"#687385":"#8b97aa"},grid:{vertLines:{color:light?"#eee":"#18202d"},horzLines:{color:light?"#eee":"#18202d"}},timeScale:{timeVisible:true}});series=chart.addCandlestickSeries({upColor:"#18c784",downColor:"#ea3943",borderUpColor:"#18c784",borderDownColor:"#ea3943",wickUpColor:"#18c784",wickDownColor:"#ea3943"});load();connect()}
async function load(){const r=await fetch(`${API}/api/v3/klines?symbol=BTCUSDT&interval=${interval}&limit=300`),a=await r.json();series.setData(a.map(x=>({time:x[0]/1000,open:+x[1],high:+x[2],low:+x[3],close:+x[4]})));const t=await(await fetch(`${API}/api/v3/ticker/24hr?symbol=BTCUSDT`)).json();$("price").textContent="$"+Number(t.lastPrice).toLocaleString("en-US",{maximumFractionDigits:2});$("change").textContent=Number(t.priceChangePercent).toFixed(2)+"%";$("high").textContent="$"+Number(t.highPrice).toLocaleString();$("low").textContent="$"+Number(t.lowPrice).toLocaleString();depth()}
async function depth(){const x=await(await fetch(`${API}/api/v3/depth?symbol=BTCUSDT&limit=10`)).json();$("asks").innerHTML=x.asks.slice(0,7).map(a=>`<div class="row ask"><span>${(+a[0]).toFixed(2)}</span><span>${(+a[1]).toFixed(4)}</span></div>`).join("");$("bids").innerHTML=x.bids.slice(0,7).map(a=>`<div class="row bid"><span>${(+a[0]).toFixed(2)}</span><span>${(+a[1]).toFixed(4)}</span></div>`).join("")}
function connect(){ws=new WebSocket(`wss://stream.binance.com:9443/ws/btcusdt@ticker`);ws.onopen=()=>$("status").textContent="● Conectado em tempo real";ws.onmessage=e=>{const x=JSON.parse(e.data);$("price").textContent="$"+Number(x.c).toLocaleString("en-US",{maximumFractionDigits:2});$("change").textContent=Number(x.P).toFixed(2)+"%"};ws.onclose=()=>{ $("status").textContent="● Reconectando...";setTimeout(connect,2000)}}
document.querySelectorAll(".tools button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tools button").forEach(x=>x.classList.remove("active"));b.classList.add("active");interval=b.dataset.i;load()});
$("theme").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("theme",document.body.classList.contains("light")?"light":"dark");theme()};
$("logout").onclick=()=>{sessionStorage.removeItem("btc_logged_in");location.href="login.html"};
init();